21 lines (14 sloc)  378 Bytes

### live server test 

GET http://localhost:8000


## ==================== Admin registration and login

### Admin user register 

POST http://localhost:8000/api/v1/registerloginRouter
Content-Type: application/json

{
    
    "lName": "Shrestha",
    "Dob": "2020-02-20",
    "phone":"044444444",
    "email": "asdfasdf@gmail.com",
    "address": "Sydney",
    "password": "12345"
}

### Admin login

POST http://localhost:8000/login
Content-Type: application/json

{
    
    "email": "bibekheores@gmail.com",
    "password": "Bibek"
}

### post category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "status":"inactive",
    "name":"Electronic",
    "parentCatId":null
} 