
### Client User Register 

POST http://localhost:8001/api/v1/register
Content-Type: application/json

{
    "fName":"Bibek",
    "lName": "Shrestha",
    "dob": "2020-02-20",
    "phone":"044444444",
    "email": "bibekheroes@gmail.com",
    "address": "Sydney",
    "password": "123dsf45",
    "address":"sydney"
}



### Client User Login 

POST http://localhost:8001/api/v1/login
Content-Type: application/json

{
    "email": "bibekheroes@gmail.com",
    "password": "123dsf45"
}


### Request OTP
POST http://localhost:8001/api/v1/register/otp
Content-Type: application/json

{
    "email": "bibekheroes@gmail.com"
}


